



spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/haircut?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    enabled: true
    servlet:
      content-type: text/html
    cache: false
  freemarker:
    template-loader-path: classpath:/templates/
    charset: UTF-8
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
  mvc:
    static-path-pattern: /**
#  redis:
#    host: 115.29.173.175
#    port: 6379
#    jedis:
#      pool:
#        max-active: 100
#        max-wait: 3000ms
#        min-idle: 0
#        max-idle: 20
#    timeout: 3000ms

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.mi.haircut.domain


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql
  page-size-zero: true


server:
  servlet:
    context-path: /haircut
  port: 8080


logging:
  file:
    path: E:/logs


wechat:
  mpAppId:   wxd364b79e3d234415    #wx5904758eb34b27d1
  mpAppSecret: 763a51818670ef800bb6e1507cc4eb79 #c14567d2bfc1bd1f1091cca02c8fe7c8
  mchId: 1492927442
  mchKey: a1b2c3D4F5G6H7J8K9l10o11p12q13zx
  keyPath:  /usr/local/wxcert/apiclient_cert.p12 #D:\Program Files\WXCertUtil\cert\apiclient_cert.p12
  notifyUrl: http://www.gouptea.top/haircut/pay/notify
